# Generated by Django 4.0.4 on 2022-05-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_id_alter_reviewrating_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy',
            field=models.IntegerField(default=0),
        ),
    ]
