# Generated by Django 4.0.4 on 2022-05-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='totalpriceget',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
